### ISSUE TITLE
NPE on password checking

### ISSUE THREAD

**Issue by scriptin** [lexaz777/NetChat2017#2]
https://github.com/lexaz777/NetChat2017/blob/69ee4840aad073890fbf2020e1578df3de9cd08c/src/ru/geekbrains/chat/server/AuthService.java#L17

`Map.get()` can return `null`, hence equality check must be reversed. Suggested change:

    username != null && password != null && password.equals(userdb.get(username));

**Comment by lexaz777** [comment]
Thank you. I resolved NPE with your help.

**Comment by scriptin** [comment]
You can close issues automatically by providing a commit message like `fix #2`: https://help.github.com/articles/closing-issues-using-keywords/
